version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: smartleads-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - smartleads-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smartleads-api
    restart: unless-stopped
    ports:
      - '5000:5000'
    environment:
      PORT: 5000
      MONGODB_URI: mongodb+srv://mystudyprojectwork_db_user:smart-leads@cluster0.6egogyl.mongodb.net
      JWT_SECRET: ${JWT_SECRET:-secrectkey}
      JWT_EXPIRES_IN: 7d
      ALLOWED_ORIGINS: http://localhost:5173
      NODE_ENV: production
    depends_on:
      - mongo
    networks:
      - smartleads-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smartleads-ui
    restart: unless-stopped
    ports:
      - '5173:80'
    depends_on:
      - backend
    networks:
      - smartleads-net

volumes:
  mongo-data:

networks:
  smartleads-net:
    driver: bridge
